import type {BrandKey,DiscoveryField} from "./engine";
export type DiscoveryAnswer=Record<string,string>;
export type DiscoveryNode=DiscoveryField&{required?:boolean;help?:string};
const common:DiscoveryNode[]=[{id:"organization",label:"Who are we creating this for?",type:"text",required:true},{id:"location",label:"Where will the experience take place?",type:"text",required:true},{id:"timeline",label:"When should this be ready?",type:"text",required:true},{id:"budget",label:"What investment range has been considered?",type:"choice",options:["Under $10K","$10K–$25K","$25K–$50K","$50K–$100K","$100K–$250K","$250K+","Not established"]}];
const studio:DiscoveryNode[]=[{id:"projectType",label:"What are we designing?",type:"choice",options:["Church AVL","Festival / Concert","LED / Video","Private Event","System Upgrade"],required:true},{id:"capacity",label:"What is the room or audience capacity?",type:"number",required:true},{id:"existing",label:"What production infrastructure already exists?",type:"text"},{id:"vision",label:"What should people feel, see and hear?",type:"text",required:true},{id:"broadcast",label:"Is broadcast or IMAG part of the experience?",type:"choice",options:["Yes","No","Unsure"]},{id:"led",label:"Should LED be part of the visual environment?",type:"choice",options:["Yes","No","Explore options"]},{id:"install",label:"Is this a permanent installation or event deployment?",type:"choice",options:["Permanent","Event / temporary","Unsure"]},{id:"stewardship",label:"Would ongoing systems stewardship be valuable?",type:"choice",options:["Yes","No","Tell me more"]}];
const artist:DiscoveryNode[]=[{id:"eventType",label:"What are we creating?",type:"choice",options:["Private Event","Concert","Featured Artist","Musical Direction","Music Production"],required:true},{id:"guestCount",label:"How many guests or attendees are expected?",type:"number"},{id:"experience",label:"Describe what you want the audience to remember.",type:"text",required:true},{id:"ensemble",label:"What performance scale are you considering?",type:"choice",options:["Solo","Duo","Rhythm Section","Horns","Strings","Full R&B Orchestra","Recommend for me"]},{id:"production",label:"Will production support be needed?",type:"choice",options:["Yes","No","Unsure"]},{id:"travel",label:"Will travel or lodging be required?",type:"choice",options:["Yes","No","Unsure"]}];

const bassOne:DiscoveryNode[]=[{id:"instrumentType",label:"What are you looking to create?",type:"choice",options:["Standard Instrument","Custom Instrument","Bespoke Commission"],required:true},{id:"strings",label:"How many strings?",type:"choice",options:["4","5","6","Other"],required:true},{id:"playerGoals",label:"What should this instrument make possible for you?",type:"text",required:true},{id:"tone",label:"Describe the tonal character you want.",type:"text"},{id:"ergonomics",label:"Any ergonomic or physical priorities?",type:"text"}];
const consulting:DiscoveryNode[]=[{id:"engagementType",label:"What kind of engagement do you need?",type:"choice",options:["Consulting","Strategy","Organizational Development","Executive Engagement"],required:true},{id:"challenge",label:"What challenge or opportunity should we address?",type:"text",required:true},{id:"outcome",label:"What would a successful outcome look like?",type:"text",required:true},{id:"stakeholders",label:"Who are the key stakeholders?",type:"text"}];
export function discoveryFor(brand:BrandKey):DiscoveryNode[]{if(brand==="studio2016")return [...studio,...common];if(brand==="jermaine"||brand==="charmin"||brand==="charminJermaine")return [...artist,...common];if(brand==="bassOne")return [...bassOne,...common];if(brand==="cgSuccess")return [...consulting,...common];return common;}
export function visibleQuestions(brand:BrandKey,a:DiscoveryAnswer){return discoveryFor(brand).filter(q=>!q.showWhen||a[q.showWhen.field]===q.showWhen.equals)}
export function completion(brand:BrandKey,a:DiscoveryAnswer){const qs=visibleQuestions(brand,a);const req=qs.filter(q=>q.required);const done=req.filter(q=>String(a[q.id]||"").trim()).length;return {required:req.length,answered:done,complete:done===req.length};}